Repository darealstyl/TeamJ-soen341project2022, pull requests merged in 2022-02, with the labels that each got.

#29 Created a skeleton for the Browsing page with styling
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/components/Product.js
  frontend/src/components/Rating.js
  frontend/src/index.css
  frontend/src/screens/BrowsingScreen.js
  frontend/src/screens/HomeScreen.js
Labels: enhancement

#42 Implementation of user profile editing page
  frontend/src/accounts.js
  frontend/src/screens/UserProfileScreen.js
Labels: user story, task

#33 Changes added to product.js class
  frontend/src/products.js
Labels: bug

#75 Added more products
  frontend/src/products.js
Labels: enhancement

#73 Updated css file
  frontend/src/index.css
Labels: documentation

#74 Updated browsing page
  frontend/src/screens/BrowsingScreen.js
Labels: documentation

#72 Deletion of code
  frontend/src/screens/BrowsingScreen.js
Labels: duplicate

#71 Adding new products
  frontend/src/products.js
Labels: enhancement
