Repository darealstyl/TeamJ-soen341project2022, pull requests merged in 2022-04, with the labels that each got.

#92 New Images
  frontend/public/images/Ipad pro.jpg
  frontend/public/images/echo.jpg
  frontend/public/images/mx mouse.jpeg
  frontend/public/images/sonos.jpeg
Labels: enhancement

#93 Cart functionality
  frontend/src/actions/cartActions.js
Labels: enhancement, Core Feature

#94 New Routes and imports Created
  frontend/src/App.js
Labels: enhancement

#95 Changes to preview of product text & ratings
  frontend/src/components/Product.js
Labels: enhancement

#110 Added cartreducer
  frontend/src/store.js
Labels: enhancement, Core Feature

#96 Implemented text component
  frontend/src/components/Rating.js
Labels: bug

#97 Checkout Steps
  frontend/src/components/CheckoutSteps.js
Labels: enhancement

#98 Cart Functionality
  frontend/src/constants/cartConstants.js
Labels: Core Feature

#99 Cart Functionality
  frontend/src/reducers/cartReducers.js
Labels: Core Feature

#100 Enhanced product view
  frontend/src/screens/BrowsingScreen.js
Labels: enhancement

#101 Cart Screen
  frontend/src/screens/CartScreen.js
Labels: Core Feature

#102 PlaceOrder Screen
  frontend/src/screens/PlaceOrderScreen.js
Labels: enhancement, Core Feature

#103 Additional features added to Product Screen
  frontend/src/screens/ProductScreen.js
Labels: bug

#107 Late Version documentation
  backend/backend/settings.py
Labels: documentation

#108 Latest version documentation
  backend/backend/urls.py
Labels: documentation

#105 Styling for headers
  frontend/src/index.css
Labels: enhancement

#106 Don't need product.js file anymore
  frontend/src/products.js
Labels: invalid

#117 added Cart Badge to header indicating number of products currently in cart
  frontend/src/actions/cartActions.js
  frontend/src/components/Header.js
Labels: enhancement, Subtask

#118 Wassim sprint4
  backend/backend/__pycache__/settings.cpython-39.pyc
  backend/backend/__pycache__/urls.cpython-39.pyc
  backend/backend/__pycache__/wsgi.cpython-39.pyc
  backend/backend/settings.py
  backend/base/__pycache__/admin.cpython-39.pyc
  backend/base/__pycache__/models.cpython-39.pyc
  backend/base/__pycache__/serializers.cpython-39.pyc
  backend/base/admin.py
  backend/base/all_views/__pycache__/order_views.cpython-39.pyc
  backend/base/all_views/__pycache__/product_views.cpython-39.pyc
  backend/base/all_views/__pycache__/user_views.cpython-39.pyc
  backend/base/all_views/user_views.py
  backend/base/migrations/0004_useraccount.py
  backend/base/migrations/0005_rename_useraccount_account.py
  backend/base/migrations/__pycache__/0004_useraccount.cpython-39.pyc
  backend/base/migrations/__pycache__/0005_rename_useraccount_account.cpython-39.pyc
  backend/base/models.py
  backend/base/serializers.py
  backend/base/urls/__pycache__/order_urls.cpython-39.pyc
  backend/base/urls/__pycache__/product_urls.cpython-39.pyc
  backend/base/urls/__pycache__/user_urls.cpython-39.pyc
  backend/db.sqlite3
  frontend/src/actions/userActions.js
  frontend/src/components/Header.js
  frontend/src/index.css
  frontend/src/screens/BrowsingScreen.js
  frontend/src/screens/SignUpScreen.js
Labels: Core Feature

#123 Search functionality and Pagination
  backend/backend/__pycache__/settings.cpython-310.pyc
  backend/backend/__pycache__/urls.cpython-310.pyc
  backend/backend/__pycache__/wsgi.cpython-310.pyc
  backend/base/__pycache__/models.cpython-310.pyc
  backend/base/__pycache__/serializers.cpython-310.pyc
  backend/base/all_views/__pycache__/product_views.cpython-310.pyc
  backend/base/all_views/product_views.py
  backend/base/urls/__pycache__/product_urls.cpython-310.pyc
  frontend/src/actions/productActions.js
  frontend/src/components/Header.js
  frontend/src/components/Paginate.js
  frontend/src/components/SearchBox.js
  frontend/src/reducers/productReducers.js
  frontend/src/screens/BrowsingScreen.js
  frontend/src/screens/ProductListScreen.js
Labels: enhancement

#122 Added product review functionality
  frontend/src/actions/productActions.js
  frontend/src/constants/productConstants.js
  frontend/src/reducers/productReducers.js
  frontend/src/screens/ProductScreen.js
  frontend/src/store.js
Labels: enhancement, user story

#125 Styling, small fix to reviews
  backend/base/all_views/product_views.py
  backend/db.sqlite3
  frontend/src/components/Header.js
  frontend/src/components/Paginate.js
  frontend/src/components/SearchBox.js
  frontend/src/index.css
  frontend/src/screens/ProductListScreen.js
Labels: enhancement

#134 Creation of Admin Product List and bug fixes
  backend/base/all_views/product_views.py
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/components/Paginate.js
  frontend/src/screens/AdminProductListScreen.js
  frontend/src/screens/ProductEditScreen.js
  frontend/src/screens/ProductScreen.js
  frontend/src/screens/SignUpScreen.js
Labels: bug, enhancement

#133 Update ProductListScreen.js
  frontend/src/screens/ProductListScreen.js
Labels: bug

#137 Update of Cart Reducers Cases
  frontend/src/reducers/cartReducers.js
Labels: enhancement

#138 Update of The App.js file route path
  frontend/src/App.js
Labels: enhancement

#144 Added orders to Profile Screen
  frontend/src/components/Header.js
  frontend/src/screens/ProfileScreen.js
Labels: enhancement

#146 bugfix: Registering for an account
  backend/base/all_views/user_views.py
  backend/db.sqlite3
  frontend/src/screens/SignUpScreen.js
Labels: bug

#147 test code in a testing framework
  Pylint_Testing_results.txt
Labels: documentation
